<a href="https://colab.research.google.com/github/adam-bozman/hypothetical-sabbatical/blob/main/MonteCarloExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This is a simple example of a Monte Carlo Simulation in Python.

In [24]:
import pandas as pd
import numpy as np
import scipy as sp
import numpy.random as npr
import pandas_datareader as pdr
import seaborn
seaborn.set()
import matplotlib.pyplot as plt
%matplotlib


Using matplotlib backend: agg


In [25]:
#Suppose you have an IRA currently valued at $100,000 invested in the S&P
#How much should you expect in your retirement account?

pv = 100000
er = .095
time_horizon = 30
ending_balance = 0

In [26]:
#deterministic method
print("{:10s} {:15s}".format("Year", "Ending Balance"))
print("-"*26)
for year in range(1, time_horizon + 1):
  ending_balance = pv * (1 + er)
  print("{:<10d} {:15,.0f}".format(year, ending_balance))
  pv = ending_balance

Year       Ending Balance 
--------------------------
1                  109,500
2                  119,902
3                  131,293
4                  143,766
5                  157,424
6                  172,379
7                  188,755
8                  206,687
9                  226,322
10                 247,823
11                 271,366
12                 297,146
13                 325,375
14                 356,285
15                 390,132
16                 427,195
17                 467,778
18                 512,217
19                 560,878
20                 614,161
21                 672,507
22                 736,395
23                 806,352
24                 882,956
25                 966,836
26               1,058,686
27               1,159,261
28               1,269,391
29               1,389,983
30               1,522,031


In [40]:
pv = 100000
er = .095
time_horizon = 30
ending_balance = 0
volatility = .185

print("{:10s} {:15s}".format("Year", "Ending Balance"))
print("-"*26)
for year in range(1, time_horizon + 1):
  year_return = npr.normal(er, volatility)
  ending_balance = pv * (1 + er)
  print("{:<10d} {:15,.0f}".format(year, ending_balance))
  pv = ending_balance

Year       Ending Balance 
--------------------------
1                  109,500
2                  119,902
3                  131,293
4                  143,766
5                  157,424
6                  172,379
7                  188,755
8                  206,687
9                  226,322
10                 247,823
11                 271,366
12                 297,146
13                 325,375
14                 356,285
15                 390,132
16                 427,195
17                 467,778
18                 512,217
19                 560,878
20                 614,161
21                 672,507
22                 736,395
23                 806,352
24                 882,956
25                 966,836
26               1,058,686
27               1,159,261
28               1,269,391
29               1,389,983
30               1,522,031


In [41]:
#incorporate volatility (higher to help incorporate inflation)
# volatility = .185

In [42]:
exp_return = .095
sd = .185
horizon = 30
iterations = 50000
starting = 100000
ending = 0

In [43]:
returns = np.zeros((iterations, horizon))
for t in range(iterations):
  for year in range (horizon):
    returns[t][year] = npr.normal(exp_return, sd)
returns[2]

array([ 1.49805258e-01, -8.86842362e-05,  2.33749017e-01,  4.22353406e-01,
       -9.67942365e-02, -5.07780753e-02, -1.43406596e-01,  1.61542337e-01,
       -1.69949005e-01,  6.82227535e-02,  2.86896431e-01, -1.10182245e-01,
        8.25887271e-02, -7.74299702e-02,  7.38687755e-02,  1.22682150e-01,
       -5.80077036e-02,  2.55936490e-01,  1.42737044e-01,  2.71899082e-01,
        6.23484346e-02,  3.82683651e-02,  5.11578894e-02,  3.68002495e-02,
        2.00320873e-02,  2.12877283e-01,  2.05448942e-01,  1.11251799e-01,
        1.83445067e-01,  2.71188860e-01])

In [44]:
portfolio = np.zeros((iterations, horizon))
for iteration in range(iterations):
  starting = 100000
  for year in range (horizon):
    ending = starting * (1 + returns[iteration,year])
    portfolio[iteration,year] = ending
    starting = ending

In [45]:
portfolio[300]

array([127267.19698276, 183984.1746682 , 239055.89681378, 319384.82709056,
       358270.61393656, 414830.52127353, 287748.17653749, 269153.46665801,
       260230.01650377, 181894.45016577, 167775.23058503, 223022.84861225,
       238920.43821078, 278415.83575794, 337149.56452872, 358653.25975672,
       302632.65100281, 252441.45510973, 271454.75305103, 290521.98297698,
       315274.19348009, 386761.82704166, 306654.69809922, 332293.40490258,
       369004.55490223, 397160.2449457 , 448045.73145244, 565694.88961686,
       657797.86065286, 901961.80403826])

In [46]:
portfolio = pd.DataFrame(portfolio).T
portfolio[list(range(5))]

0             1             2             3             4
0   105082.381385  1.494878e+05  1.149805e+05  9.467819e+04  1.137274e+05
1   154125.787591  1.323901e+05  1.149703e+05  1.241152e+05  1.226261e+05
2   156529.182913  1.740638e+05  1.418445e+05  1.127295e+05  1.517010e+05
3   155860.843904  1.567298e+05  2.017531e+05  7.631063e+04  1.537098e+05
4   142917.639549  1.713038e+05  1.822245e+05  9.705084e+04  1.683270e+05
5   147418.284991  2.236423e+05  1.729715e+05  9.948531e+04  2.154002e+05
6   181675.224450  2.902983e+05  1.481663e+05  1.141803e+05  2.567019e+05
7   141672.812875  3.159770e+05  1.721014e+05  1.220467e+05  2.752826e+05
8   149032.474654  3.417075e+05  1.428529e+05  1.522345e+05  2.870897e+05
9   113269.395804  3.624005e+05  1.525987e+05  1.686113e+05  3.385124e+05
10  133402.589371  4.163933e+05  1.963788e+05  1.614457e+05  3.771093e+05
11  130178.929667  3.754675e+05  1.747413e+05  1.987881e+05  3.738717e+05
12  119523.172534  3.437909e+05  1.891730e+05  2.577162e+05  4.065620e+05
13  141649.645589  4.035971e+05  1.745253e+05  3.058463e+05  5.528444e+05
14  156745.738910  4.069317e+05  1.874173e+05  3.947839e+05  3.956227e+05
15  142609.214185  3.404407e+05  2.104100e+05  4.777726e+05  3.624462e+05
16  178425.080011  3.641716e+05  1.982046e+05  4.226763e+05  3.443406e+05
17  181261.191805  3.932836e+05  2.489324e+05  4.626824e+05  4.195924e+05
18  246695.214790  5.233780e+05  2.844643e+05  7.193202e+05  3.601296e+05
19  295043.082022  6.919976e+05  3.618099e+05  8.253569e+05  4.196952e+05
20  209185.111300  5.033211e+05  3.843682e+05  7.285310e+05  5.090638e+05
21  176053.554535  6.981306e+05  3.990773e+05  6.380618e+05  6.387753e+05
22  250975.670903  8.643579e+05  4.194933e+05  4.576892e+05  6.786000e+05
23  253704.906140  1.040709e+06  4.349308e+05  4.938850e+05  6.062425e+05
24  261533.222882  1.175142e+06  4.436433e+05  6.235094e+05  6.117530e+05
25  254149.354863  1.245209e+06  5.380849e+05  7.678965e+05  6.656258e+05
26  248857.089635  9.542793e+05  6.486339e+05  7.709275e+05  7.200308e+05
27  275068.141263  1.078345e+06  7.207956e+05  1.052379e+06  1.064380e+06
28  279212.964935  1.493652e+06  8.530220e+05  1.645959e+06  1.331676e+06
29  332478.749467  1.713454e+06  1.084352e+06  1.500216e+06  9.383633e+05

In [47]:
portfolio.iloc[29].describe()

count    5.000000e+04
mean     1.523063e+06
std      1.700287e+06
min      1.063273e+04
25%      5.188605e+05
50%      9.967529e+05
75%      1.892115e+06
max      3.529640e+07
Name: 29, dtype: float64

In [48]:
ending = portfolio.iloc[29]
mask = ending < 10000000
plt.figure(figsize=(12,8))
plt.xlim(ending[mask].min(), ending[mask].max() )
plt.hist(ending[mask], bins=100, edgecolor='k')
plt.axvline(ending[mask].median(), color='r')

In [49]:
percentiles = [1,5,10]
np.percentile(ending, percentiles)

array([ 94034.75662153, 194556.09227591, 279905.11837378])